public enum SelectSound
{
    Background,
    Arrow,
    GameOver,
    Sword,
    SwordBlood,
    Heal,
    Pickup,
    EnemyAttack,
    Dash,
    Combat,
    Attack2,
    MonsterBreath,
    Victory,
    ClickBtn,
    ResonanceSkill,
    HealBossLevel1,
    CreateMini,
    BossShoot,
    BossBringerShoot,
    SpellBossBringer,
    MusicInsideCave
}
